### PR TITLE
Request Handler: Edit PlayPauseMedia

### PR DESCRIPTION
**Pull request by cpyarger**
### Description
Remove the Requirement for the boolean value, and implement a toggle function if no boolean parameter exists

### Motivation and Context
A friend asked me to add this feature

### How Has This Been Tested?

Tested OS(s): 
Tested on windows
### Types of changes

 - Enhancement (modification to a current event/request which adds functionality) 

### Checklist:

-   [*] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [*] My code is not on the master branch.
-   [*] The code has been tested.
-   [*] All commit messages are properly formatted and commits squashed where appropriate.
-   [*] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Please follow the commit guidelines for your commit titles. You also include updates to both dependencies in this PR which should not be included.

**Comment by cpyarger** [comment]
I am unable to figure out how to properly fix this on this PR, Creating a new one with the requested changes

**Comment by cpyarger** [comment]
Oops I did not mean to close that

**Comment by cpyarger** [comment]
Wait, Yes I did, This is the old request

**Pull request closed without merging**
