### PR TITLE
general(notifications): Toggle tray notifications/alerts (Closes #120)

### LINKED ISSUE #120: Obs-websocket and query strings
##### Issue type
Feature request

##### Description
Recently found out about obs-websocket and really appreciate the work. Unfortunately due to the lack of knowledge in programming can't get to work using js. Is it possible to control OBS just sending commands to obs-websocket using query strings like:
localhost:4444/?switchscene=game

If not, what is the easiest way to write a script that does simple things like that?

Thanks a lot!

### PR DESCRIPTION
**Pull request by haganbmj**
Closes #120 
Adds a config toggle to enable/disable tray notifications when a client connects.

I don't have OBS installed on this machine at the moment so I didn't get a chance to visually inspect the settings dialog placement.

### CODE REVIEW

**Comment by Palakis** [comment]
Thanks, I'll test this.

> I don't have OBS installed on this machine at the moment so I didn't get a chance to visually inspect the settings dialog placement.

Was the new setting widget added with Qt Creator ? If so, it's pretty much the same as at runtime, except when using special layout stuff.

**Comment by haganbmj** [comment]
ah, I don't use creator. I just guess at x/y values.

**Comment by haganbmj** [comment]
I haven't actually used OBS for anything in about a year. I travel weekly for work and haven't had the time to record/stream anything.

**Comment by haganbmj** [comment]
obs_notifications

Got around to checking the positioning. Looks fine.

**Pull request merged**
