### PR TITLE
Docs: Add another Go client library

### PR DESCRIPTION
**Pull request by andreykaipov**
### Description
The existing Go client doesn't seem to be supported anymore so I made my own at https://github.com/andreykaipov/goobs for the v4.9.1 protocol, and I plan on updating it when v5 is ready! 😄

### Types of changes
Documentation change

### Checklist:

-   [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [x] My code is not on the master branch.
-   [x] The code has been tested.
-   [x] All commit messages are properly formatted and commits squashed where appropriate.
-   [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
If the existing library is not being supported anymore, please commit its removal as part of the PR.

**Comment by andreykaipov** [comment]
> If the existing library is not being supported anymore, please commit its removal as part of the PR.

Sorry I wouldn't feel super comfortable removing somebody else's library! 😅

It's more than just that one though. There's a few libraries on that list that haven't been updated in a while. Maybe it might be better to go through and remove them together in a separate PR, perhaps noting the criteria to remain on the list?

**Comment by tt2468** [comment]
If you don't want to, then thats fine. This list is going to be reset in 5.0.0 anyway.

**Review by tt2468 — APPROVED** [review]

**Comment by andreykaipov** [comment]
Sounds good to me! 👀 Thanks!

**Pull request merged**
