### PR TITLE
docs: update glob to account for relocation to src

### PR DESCRIPTION
**Pull request by haganbmj**
Wrote this glob originally to avoid accidentally pulling in the third party `deps` directory.

### CODE REVIEW

**Comment by Palakis** [comment]
Oops, I fixed that an hour ago.
But there's another issue: docs.js fails to generate the new protocol reference document.

See https://travis-ci.org/Palakis/obs-websocket/jobs/301497580
```
> obs-websocket-docs@1.0.0 docs /home/travis/build/Palakis/obs-websocket/docs
> node ./docs.js
/home/travis/build/Palakis/obs-websocket/docs/docs.js:11
    return text.replace('|', `\\|`);
               ^
TypeError: Cannot read property 'replace' of undefined
    at Object.handlebars.registerHelper (/home/travis/build/Palakis/obs-websocket/docs/docs.js:11:16)
    at eval (eval at createFunctionContext (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:70)
    at prog (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:31)
    at Object.prog [as fn] (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Object.<anonymous> (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at eval (eval at createFunctionContext (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:14:32)
    at prog (/home/travis/build/Palakis/obs-websocket/docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
```

**Comment by Palakis** [comment]
Btw, regarding the glob itself, I believe it's fine to target `src/` specifically. It can easily expanded to other directories if needed. This can be reminded in a future version of the Contributing guidelines.

**Comment by haganbmj** [comment]
Added a quick check there to cover that helper function, but that's probably indicative of some error in the source documentation.

**Comment by Palakis** [comment]
> but that's probably indicative of some error in the source documentation.

Ow.

**Comment by Palakis** [comment]
By "source documentation", do you mean the actual comments or comments.json?

**Comment by haganbmj** [comment]
That method is only used when parsing the `type` of a request/response item.
Found a missing bracket. I'd like to find a better way to handle that with logging, but there isn't a whole lot of context there to work with.

**Comment by haganbmj** [comment]
Yeah, certainly.
I'll see about making it more robust and making it a bit more clear where the in/out paths are.

The only reason that depipe function is there is to account for the types being `{ Array | String }` or something since the `|` character would get interpreted as a markdown table column.

**Pull request merged**
