### PR TITLE
docs: Mark from-scene as optional

### PR DESCRIPTION
**Pull request by dnaka91**
### Description

The `from-scene` property of the `TransitionBegin` and `TransitionVideoEnd` is optional but is not marked as such in the docs. 

Originally discovered in [obws](https://github.com/dnaka91/obws/pull/8).

### Motivation and Context

As this field wasn't marked as optional I added it as required field in `obws` which causes deserialization to fail if it's missing. It's already fixed there but should be updated here for correctness and future library writers.

### How Has This Been Tested?

Tested OS(s): Tested through the `obws` library with latest OBS and obs-websocket.

### Types of changes

- Documentation change (a change to documentation pages)

### Checklist:

-   [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [x] My code is not on the master branch.
-   [x] The code has been tested.
-   [x] All commit messages are properly formatted and commits squashed where appropriate.
-   [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Your PR seems to include quite a few unnecessary changes: https://github.com/Palakis/obs-websocket/pull/706/files

The only file that needs changing is `WSEvents.cpp`. Everything else will be automatically committed once the PR is merged.

Also, is it truly optional or is it never sent? Because according to [here](https://github.com/Palakis/obs-websocket/blob/4.x-current/src/Utils.cpp#L501), it might just never be sent. In which case we should remove the field entirely.

**Comment by dnaka91** [comment]
True, it's very unlikely that there will ever be a transition to the same scene right?

I ran the docs generation manually and included the changes. Will revert that part back then.
Should I revert the whitespace trimming changes as well?

**Comment by tt2468** [comment]
> Should I revert the whitespace trimming changes as well?

Not strictly necessary, just the generated docs files and whatever `docs/npm-shrinkwrap.json` is

**Comment by dnaka91** [comment]
Oh I'm so sorry. I didn't even realize that file slipped in there. Removed it now together with the unneeded docs changes 🙇

**Review by tt2468 — APPROVED** [review]

**Pull request merged**
