### PR TITLE
Added reference to a Dart API

### PR DESCRIPTION
**Pull request by faithoflifedev**
### How Has This Been Tested?

Tested OS(s): 

### Checklist:

-   [ ] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [ ] My code is not on the master branch.
-   [ ] The code has been tested.
-   [ ] All commit messages are properly formatted and commits squashed where appropriate.
-   [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tt2468** [comment]
Please follow the commit guidelines in the contributing document: https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md

**Comment by faithoflifedev** [comment]
HI @tt2468, I just read through the "contributing" doc.  The submitted PR is just adding a line to the README.md, is it still necessary to create an alternate branch and resubmit the PR, in this case?

**Comment by tt2468** [comment]
If you used the git command line, you can just use `git commit --amend` to edit your commit title, then `git push --force` to force push the changes.

**Comment by tt2468** [comment]
It also appears that the branch you are PR-ing from is your local 4.x-current, which is not allowed. I'll go ahead and close this and open a PR for you.

**Pull request closed without merging**
